add templategroup module to project
ansible-collections/community.zabbix pull request #1104
Opened 2023-10-18 20:10 UTC by natemccallum

##### SUMMARY
Added a template group module that leverages the templategroup api methods (get, create, delete)

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
zabbix_templategroup

##### ADDITIONAL INFORMATION
I was looking for a way to add template groups and couldn't find one. I simply copied the zabbix_group module and tailored for template groups.

2023-10-22 19:53 UTC, pyrodie18 requested changes
Please look at the actions log and fix the failures.  Also add a change framgement.

2023-10-25 00:47 UTC, pyrodie18 approved these changes

2023-10-25 00:48 UTC, pyrodie18 commented
@BGmot

2023-12-14 01:19 UTC, cjohannsen81 commented
@pyrodie18 Any chance to get this one merged?

2023-12-17 16:13 UTC, merged