Management of the Windows agent installation and some variables.
ansible-collections/community.zabbix pull request #1120
Opened 2023-11-10 09:26 UTC by KhatibMechentel

##### SUMMARY

Role zabbix_agent :

- Windows agent installation : Management of the uninstallation of the old version of the agent

- New variables  : Linux plugins directory, Windows  

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

- zabbix_agent role

##### ADDITIONAL INFORMATION

```paste below

```

2023-11-11 04:12 UTC, pyrodie18 requested changes
Please see inline comments.  Please add change fragment, and also update the documentation with the variables that you added.

2023-11-11 04:12 UTC, pyrodie18 commented on roles/zabbix_agent/tasks/Windows.yml
> -  ansible.builtin.set_fact:
Not sure why you moved away from fully qualified modules, but please put them back in place

2023-11-11 04:12 UTC, pyrodie18 commented on roles/zabbix_agent/templates/zabbix_agent2.conf.j2
> -{% endif %}
Is there a reason to get rid of this block?

2023-11-18 08:56 UTC, KhatibMechentel commented
Hello.
I'm going to work on another feature.
I close this one.

2023-11-18 08:56 UTC, closed without merging