Add template_yaml parameter to zabbix_template module
ansible-collections/community.zabbix pull request #1157
Opened 2024-01-05 05:26 UTC by masa-orca

##### SUMMARY

- Adding template_yaml parameter to zabbix_template module.
- Using [configuration.importcompare](https://www.zabbix.com/documentation/current/en/manual/api/reference/configuration/importcompare) to compare  template file(not only yaml but also json and xml) with Zabbix current configurations.
- Removing unused functions.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

- zabbix_template
##### ADDITIONAL INFORMATION
- A type of template_json is not `file` but `json`. Therefore, I cloudn't combine `template_XXX` parameter to a parameter.
- I cloudn't understand that `Filter the template json to contain only the keys we will update` in `filter_template` function is needed or not.

```paste below

```

2024-01-07 21:48 UTC, flowerysong commented
I don't have the time to test it right now, but this shouldn't be necessary.

The point of the `json` argument type is that it ensures that what the module receives is a consistent format regardless of whether it started as a JSON string or a data structure, so instead of complicating the module interface all you should have to do is convert the file from YAML:

```yaml
    - name: Import Zabbix template from YAML file.
      community.zabbix.zabbix_template:
        template_json: "{{ lookup('file', 'template4_60_higher.yaml') | from_yaml }}"
        state: present
      register: import_template_yaml
```

2024-01-08 09:31 UTC, masa-orca commented
@flowerysong Thank you fo your response. I understood it is not necessary. However, it is a temporally workaround that you mentioned way, isn't it?

If this pull request is waste, I'll close it.

2024-01-10 13:43 UTC, BGmot approved these changes

2024-01-10 13:46 UTC, BGmot requested changes
Changelog fragment please?

2024-01-10 14:19 UTC, BGmot approved these changes

2024-01-10 15:28 UTC, merged