Add zabbix_correlation module
ansible-collections/community.zabbix pull request #1169
Opened 2024-01-18 01:55 UTC by masa-orca

##### SUMMARY

Add new module for [correlation](https://www.zabbix.com/documentation/current/en/manual/api/reference/correlation/object)

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

zabbix_correlation
##### ADDITIONAL INFORMATION
- I don't add checks about correlation filter's fomula.

2024-01-20 05:13 UTC, pyrodie18 approved these changes

2024-01-20 05:13 UTC, pyrodie18 requested changes
Looks good.  Please add a change fragment.

2024-01-21 14:24 UTC, masa-orca commented
@pyrodie18 Thank you for your reviewing, I added changelog fragment!

2024-01-22 12:35 UTC, pyrodie18 approved these changes

2024-01-22 12:36 UTC, merged