Make Zabbix repository gpg key URL customizable
ansible-collections/community.zabbix pull request #1186
Opened 2024-02-26 13:02 UTC by jtekuelve

##### SUMMARY

The proposed change introduces a variable in the agent, javagateway, proxy, server, and web role, which replaces the hardcoded string in the "Debian | Download gpg key" task. The default value of the "zabbix_<role>_gpg_key_url" variable is the previously hardcoded string: http://repo.zabbix.com/zabbix-official-repo.key

Additionally, a second variable "zabbix_<role>_include_deb_src" with default value "true" was introduced to toggle adding deb-src in the "Debian | Installing repository {{ ansible_distribution }}" task. 

Rationale: We are deploying Zabbix via Ansible in an environment without Internet access. We are using our own package mirror, which is configurable via the "zabbix_repo_deb_url". Unfortunately, without the proposed changes, we are unable to change the download location of the gpg key from the official repo to our own mirror. The second change, making deb-src optional is another change that makes the role easier to use with a custom package mirror. In our testing, it turned out that the deb-src repo was not required. Overall, both changes should not change the current functionality given that only hardcoded parts were replaced by variables with default values.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
roles: zabbix_agent, zabbix_javagateway, zabbix_proxy, zabbix_server, and zabbix_web

##### ADDITIONAL INFORMATION
I was unsure if I set the variables at the right location (currently defaults/main.yml) of each role. One could also argue to put them in vars/Debian.yml of each role. In the current repo, the defaults already contained some os dependent vars, for example, the # Yum/APT  Variables section, therefore I added them there. I am always open to moving or renaming them. For now, I stuck with the naming scheme that prefixes the role name, but it could be confusing since, for example, "zabbix_repo_deb_url" does not stick to this naming scheme and is kind of related.

2024-02-29 23:35 UTC, pyrodie18 requested changes
Should have left this earlier but please update the readme for the roles with the new variables and then you're good to go.

2024-03-01 09:24 UTC, jtekuelve commented
After updating the readme I noticed that the other deb repository vars all start with zabbix_repo_deb. I adopted the same prefix for my variables.

2024-03-04 16:58 UTC, BGmot requested changes

2024-03-04 16:58 UTC, BGmot commented on changelogs/fragments/1186-custom_gpg_key_url.yml
> +  - agent, javagateway, proxy, server, and web role - updated readme with the two new variables "zabbix_repo_deb_gpg_key_url" and "zabbix_repo_deb_include_deb_src"
```suggestion
```
Updating README should not be mentioned in Changelog, it's just natural (the way it should be done).

2024-03-04 16:58 UTC, BGmot commented on roles/zabbix_proxy/defaults/main.yml
> +
```suggestion
```

2024-03-07 13:19 UTC, pyrodie18 approved these changes

2024-03-07 13:20 UTC, merged

2024-03-07 13:21 UTC, BGmot commented
@pyrodie18 you merged without waiting for test to complete -)))

2024-03-07 13:26 UTC, pyrodie18 commented
It had completed the first time and there were no code significant changes so ya but sorry

2024-03-07 13:27 UTC, BGmot commented
No worries -)