Add support for Ubuntu 24.04 Noble Numbat (all roles)
ansible-collections/community.zabbix pull request #1221
Opened 2024-05-07 15:54 UTC by sblaisot

##### SUMMARY

Ubuntu 24.04 Noble Numbat has been out since April 29, 2024

This pull request add support for Ubuntu 24.04 Noble Numbat using zabbix repositories. Only zabbix 6.0 and zabbix 6.4 are available in zabbix repo for Ubuntu 24.04

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

All roles

2024-05-08 15:29 UTC, sblaisot commented
I didn't manage to make tests pass with ubuntu 24.04 because it comes with python 3.12 which [requires ansible-core 2.15.3 to fix get_url](https://github.com/ansible/ansible/blob/v2.15.3/changelogs/CHANGELOG-v2.15.rst) which in turn requires ansible 8 which complain of community.docker collection not being installed. So I left tests on Ubuntu 24.04 aside from this PR (I kept it commented out). This seems to be a work beyond my capabilities and should be addressed in another PR.

2024-05-09 22:19 UTC, pyrodie18 commented
We're gonna have to figure out how to make it work with 24.04.

2024-05-14 12:45 UTC, sblaisot commented
@pyrodie18 

I finally managed to make tests run on ubuntu 24.04 \o/

I had to make some minor adjustments to make the tests pass (especially zabbix server mysql and zabbix_java_gateway package install)

There is still an issue with geerlinguy.nginx in role zabbix_web on Ubuntu 24.04 I am working on

2024-05-18 14:11 UTC, pyrodie18 requested changes

2024-05-18 14:27 UTC, sblaisot commented on molecule/requirements.txt
As I said in previous comment, ubuntu 24.04 comes with python 3.12 which [requires ansible-core 2.15.3 to fix get_url](https://github.com/ansible/ansible/pull/80751).

Upgrading to ansible-core 2.15.3; I had to upgrade to Ansible 8, which complain of community.docker collection not being installed becouse it can't find it in the directory in site-packages/ansible_collections (inside virtual env).
So I had to comment out ansible installation to avoid core collections to be installed in virtual env and have the installed later in the collections directory.

This made the tests execute correctly and pass

2024-05-18 15:09 UTC, pyrodie18 commented on molecule/requirements.txt
OK, were you using 24.04 as the ansible controller or something else?  This change would be a breaking change which we can't do until we release 3.0.0.  And even then would have to look at making it a requirement

2024-05-18 15:15 UTC, sblaisot commented on molecule/requirements.txt
no, 24.04 is the target, not the contrôler. but you can't use get_url on a 24.04 (python 3.12) target with ansible core < 2.15.3 on the controller

2024-05-18 15:16 UTC, sblaisot commented on molecule/requirements.txt
I don't see how a change in the test environment (molecule) make it a breaking change.

2024-05-18 15:43 UTC, sblaisot commented on molecule/requirements.txt
To make it clear, this collection is only tested with ansible-core 2.14.2. There is no test with ansible-core 2.15 or 2.16 (nor incoming 1.17 beta), so you currently can't tell for sure this collection will work with ansible-core 2.15+

Same for ansible, there is currently only tests with ansible 7.0.0 but the documentation says "Ansible 2.10+"

So what does it change to test with ansible8/ansible-core 2.15 instead of ansible 7/ansible-core 2.14 regarding community.zabbix requirements or supported versions?

I honestly see here no change making it a breaking change.

Could you explain your point of view?

2024-05-18 19:36 UTC, pyrodie18 commented on molecule/requirements.txt
OK I messed up.  Was thinking this was the this was the requirements file at the top level of the collection (which now that I look at it is empty).

2024-05-18 21:01 UTC, pyrodie18 approved these changes
Appreciate the PR.

2024-05-18 21:01 UTC, merged

2024-05-18 21:52 UTC, sblaisot commented
> Appreciate the PR.

Thanks to have merged this one ;)