allow nginx/apache group to write to FPM socket
ansible-collections/community.zabbix pull request #1227
Opened 2024-05-13 13:16 UTC by baszoetekouw

##### SUMMARY
In the current configuration, the web server is not allowed to write to the FPM socket, causing a "bad gateway" error, as the web server cannot forward requests over the socket.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
zabbix-web

##### ADDITIONAL INFORMATION
Before this change, the FPM socket has these permissions:
```
srw-r--r-- 1 zabbix-fpm www-data 0 May 13 13:13 /run/php/zabbix.sock
```
The web server, which runs as user/group `www-data` needs write access to this socket in order to forward requests.

With this PR applied, the socket permissions become:
```
srw-rw---- 1 zabbix-fpm www-data 0 May 13 13:15 /run/php/zabbix.sock
```

2024-05-14 02:15 UTC, pyrodie18 requested changes
Please add a change fragment

2024-05-14 07:00 UTC, baszoetekouw commented
> Please add a change fragment

Sorry, I don't know what you mean by that.

2024-05-14 12:42 UTC, pyrodie18 commented
https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment

2024-05-14 12:46 UTC, baszoetekouw commented
Thanks, I wasn't aware of that documentation.  I'll prepare the changelog!

2024-05-15 12:10 UTC, pyrodie18 requested changes

2024-05-15 12:10 UTC, pyrodie18 commented on changelogs/fragments/1227-fpm-socket-permissions.yml
Don't need to include the PR link.  It will take care of that automagically

2024-05-16 01:27 UTC, pyrodie18 commented on changelogs/fragments/1227-fpm-socket-permissions.yml
So it is.....never noticed that part before.  Either way not needed.  Thanks.

2024-05-16 01:27 UTC, pyrodie18 approved these changes

2024-05-16 01:27 UTC, merged