Bug Fix PSK value issue related to #109
ansible-collections/community.zabbix pull request #388
Opened 2021-05-28 16:59 UTC by ericsysmin

##### SUMMARY
Fixes #109 by changing the value to lowercase.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
zabbix_proxy role

##### ADDITIONAL INFORMATION
Before fix Zabbix Proxy would fail to start
```paste below
TASK [community.zabbix.zabbix_proxy : zabbix-proxy started] ****************************************************************************************
fatal: [hostname]: FAILED! => {"changed": false, "msg": "Unable to start service zabbix-proxy: Job for zabbix-proxy.service failed because the control process exited with error code.\nSee \"systemctl status zabbix-proxy.service\" and \"journalctl -xe\" for details.\n"}

May 28 07:14:17 hostname zabbix_proxy[29974]: zabbix_proxy [29974]: ERROR: invalid value of "TLSAccept" parameter
May 28 07:14:17 hostname systemd[1]: zabbix-proxy.service: Control process exited, code=exited status=1
May 28 07:14:17 hostname systemd[1]: zabbix-proxy.service: Failed with result 'exit-code'.
May 28 07:14:17 hostname systemd[1]: Failed to start Zabbix Proxy.
-- Subject: Unit zabbix-proxy.service has failed
```

After the change
```
TASK [community.zabbix.zabbix_proxy : zabbix-proxy started] ****************************************************************************************
ok: [hostname]

 zabbix-proxy.service - Zabbix Proxy
   Loaded: loaded (/lib/systemd/system/zabbix-proxy.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2021-05-28 16:55:18 UTC; 3min 7s ago
  Process: 2419 ExecStart=/usr/sbin/zabbix_proxy -c $CONFFILE (code=exited, status=0/SUCCESS)
 Main PID: 2439 (zabbix_proxy)
```

2021-05-28 18:50 UTC, ericsysmin commented
@D3DeFi can you review?

2021-05-28 20:28 UTC, D3DeFi requested changes
can you please put changelog snippet into the PR?

otherwise I think this is good to go and long overdue anyway. It just slipped our attention a while back. I can confirm it will work like this when calling zabbix_proxy module.

Not sure what else it will break tho
@dj-wasabi can you please also confirm this is good to go and will not have some other consequences?

2021-05-29 07:48 UTC, dj-wasabi approved these changes
lgtm.

2021-05-29 14:10 UTC, merged

2021-05-29 14:11 UTC, D3DeFi commented
I will be passing all of the PRs when releasing 1.4.0 this weekend and fill in missing changelogs

2021-05-29 16:19 UTC, ericsysmin commented
Ok, ya, it got merged before I had time to fill out a changelog but the change was simple enough.