Add apiinfo_facts module and tests
ansible-collections/community.zabbix pull request #733
Opened 2022-07-10 18:28 UTC by masa-orca

##### SUMMARY
Add apiinfo_facts module

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

community.zabbix.zabbix_apiinfo_facts

##### ADDITIONAL INFORMATION
- Add apiinfo_facts module and tests.
- This returns only version info now

2022-07-12 11:39 UTC, D3DeFi requested changes
Nice module addition. Thank you! :)

2022-07-12 11:39 UTC, D3DeFi commented on plugins/modules/zabbix_apiinfo_facts.py
> +        supports_check_mode=True
I would go for `False` here. You after all, do not use if `module.check_mode` anywhere and for this kind of module it is not even needed. 

```suggestion
        supports_check_mode=False
```

2022-07-28 08:55 UTC, D3DeFi approved these changes
Looks good to me :)

2022-07-28 09:00 UTC, D3DeFi commented
I may have miss-lead you with a check mode :disappointed: 

https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_general.html#creating-an-info-or-a-facts-module

it seems they must to support check mode? Probably a reason why this fails.

I am so sorry

2022-07-30 07:49 UTC, mu1f407 commented
I was just reading through documentation yesterday and noticed the requirements for info/facts modules. Beside check mode, fact modules must return `ansible_facts`. Module documentation (`RETURN`) should also reflect that. Please see [ipinfoio_facts](/ansible-collections/community.general/blob/main/plugins/modules/net_tools/ipinfoio_facts.py) as an example.

2022-08-07 08:34 UTC, BGmot commented
To be honest I'd rename this module to either zabbix_api_info or zabbix_api_facts.

2023-05-02 03:51 UTC, masa-orca commented
Hi, Reviewers.
Thank you for your reviewing. I appologize for taking much times to modify.
I read [creating-an-info-or-a-facts-module](https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_general.html#creating-an-info-or-a-facts-module) (@D3DeFi mentioned). 
The document says 
> Modules that query/return general information (and not ansible_facts) should be named _info. General information is non-host specific information, for example information on online/cloud services (you can access different accounts for the same online service from the same host), or information on VMs and containers accessible from the machine, or information on individual files or programs.

Therefor, I think it is `_info` module.

> To be honest I'd rename this module to either zabbix_api_info or zabbix_api_facts.

I agree it. I renamed module to `zabbix_api_info `.

2023-06-25 22:18 UTC, BGmot commented
Thanks a lot @masa-orca !

2023-06-25 22:21 UTC, BGmot requested changes

2023-06-25 22:21 UTC, BGmot commented on plugins/modules/zabbix_api_info.py
> +    - "python >= 2.6"
Since we are adding this module just now would you please update?
```suggestion
    - "python >= 3.9"
```

2023-06-25 22:21 UTC, BGmot commented on plugins/modules/zabbix_api_info.py
> +version_added: 1.8.0
Since we are adding this module just now would you please update?
```suggestion
version_added: 2.1.0
```

2023-06-25 22:21 UTC, BGmot commented on plugins/modules/zabbix_api_info.py
> +            sample: 4.0.42
Maybe a bit fresher example?
```suggestion
            sample: 6.0.18
```

2023-06-29 16:38 UTC, masa-orca commented
@BGmot Thank you for your reviwing! I updated documents.

2023-06-29 16:59 UTC, BGmot approved these changes

2023-07-02 08:26 UTC, masa-orca commented
I rebased main branch and added this module to action_groups.

2023-07-02 12:34 UTC, merged