Bugfix optional TLS settings
ansible-collections/community.zabbix pull request #753
Opened 2022-07-27 13:36 UTC by JeroenBo

##### SUMMARY
When tls_connect and tls_accept are not specified in the playbook it defaults to 1 which removes the current TLS/PSK settings of the host in Zabbix.

This update will remove the default value of 1 and only updates the data when needed.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
zabbix_host.py

##### ADDITIONAL INFORMATION
When tls_connect and tls_accept are not specified in the playbook it defaults to 1 which removes the current TLS/PSK settings of the host in Zabbix

2022-07-27 18:01 UTC, mu1f407 commented
Hi @JeroenBo, thank you for PR! There are some failing checks though. Could you please take a look at it? Some linter checks are failing (trailing whitespace, missing space after comma,...) and module documentation should be adjusted for changed parameter default. Also please include changelog fragment (see [CONTRIBUTING](https://github.com/ansible-collections/community.zabbix/blob/main/CONTRIBUTING.md)). Thanks!

If you need any help, just let me know.

2022-07-30 08:05 UTC, mu1f407 requested changes
@JeroenBo After requested changes I am happy to approve your PR. Thanks!

2022-07-30 08:05 UTC, mu1f407 commented on CHANGELOG.rst
> +- zabbix-agent - will no longer wipe tls_connect en tls_accept settings when not specified on update (https://github.com/ansible-collections/community.zabbix/pull/753)
Changelog shouldn't go directly into the main CHANGELOG file. Please add fragment into /changelogs/fragments directory. See existing files as an examples. This should be categorized as minor_changes.
```suggestion
---
minor_changes:
  - zabbix_host - will no longer wipe tls_connect en tls_accept settings when not specified on update
```
Above should go into /changelogs/fragments/753-host-tls-settings.yml for example.

2022-08-01 08:26 UTC, D3DeFi approved these changes
Looks good! Thank you :)

@mu1f407 your requested changes were applied.

2022-08-01 08:31 UTC, mu1f407 approved these changes

2022-08-01 08:33 UTC, merged

2022-08-01 08:35 UTC, mu1f407 commented
@JeroenBo Thank you for your contribution! Highly appreciated.