add support for ubuntu 22.04 on zabbix_web role
ansible-collections/community.zabbix pull request #786
Opened 2022-08-24 01:36 UTC by miettal

##### SUMMARY

I add support for ubuntu 22.04 on zabbix_web role.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

zabbix_web

##### ADDITIONAL INFORMATION

```paste below

```

2022-08-25 17:36 UTC, mu1f407 requested changes
Hi @miettal, thank you for the PR! Could you please add following changes?

1. Add Ubuntu 22.04 jammy into [Zabbix versions table in docs/ZABBIX_WEB_ROLE.md](https://github.com/ansible-collections/community.zabbix/blob/main/docs/ZABBIX_WEB_ROLE.md#zabbix-versions). Only Zabbix versions 6.2 and 6.0 are supported on 22.04 as only these versions support PHP 8.1 which is included in jammy.
2. Add [changelog fragment](https://docs.ansible.com/ansible/devel/community/development_process.html#creating-changelog-fragments) which summarizes this change. Something like:
    ```yaml
    ---
    minor_changes:
      - zabbix_web - add support for Ubuntu 22.04 jammy
    ```
    going into `changelogs/fragments/786-web-add-ubuntu-22-04-support.yml` would be fine.

Thanks!

2022-08-26 09:05 UTC, miettal commented
Thank you comment!
I updated document and changelog.

2022-08-26 09:07 UTC, D3DeFi approved these changes
This looks good, thank you for the PR! Will merge once CI passes

2022-08-26 09:16 UTC, mu1f407 approved these changes

2022-08-26 09:26 UTC, merged