Allow system.hw.chassis to populate on Linux
ansible-collections/community.zabbix pull request #793
Opened 2022-08-31 14:47 UTC by dgibbs64

##### SUMMARY

allow system.hw.chassis to be populated by giving zabbix group access to DMI table.

fixes #784 

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

zabbix_agent_chassis

##### ADDITIONAL INFORMATION

This task changes permissions of `/sys/firmware/dmi/tables/DMI` to `root:zabbix` and is opt-in

```paste below

```

2022-08-31 17:11 UTC, mu1f407 requested changes
Please also include [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-changelog-fragments) (see examples in _changelogs/fragments_ directory). After these small changes I'm happy with it. Thanks. :slightly_smiling_face:

2022-08-31 17:11 UTC, mu1f407 commented on roles/zabbix_agent/tasks/Linux.yml
> +  when: zabbix_agent_chassis
```suggestion
  when: zabbix_agent_chassis | bool
```
It's safer to use bool filter here, as user can pass string value (yes, true,...).

2022-09-03 16:02 UTC, pyrodie18 commented
Agree with @mu1f407 suggested changes but other than that looks good.

2022-09-03 16:03 UTC, pyrodie18 commented
Solves #784

2022-09-03 19:02 UTC, dgibbs64 commented
Thanks I will make the changes as soon as I can 😊

2022-09-06 20:45 UTC, dgibbs64 commented
Added the changelog fragment (hopefully I have don't it correctly).

2022-09-07 17:50 UTC, mu1f407 approved these changes
I'm fine with it. Thanks.

2022-09-10 07:04 UTC, D3DeFi approved these changes
Looks good! Thanks

2022-09-10 07:04 UTC, merged