Zabbix API doesn't accept IPv6 addresses
ansible-collections/community.zabbix pull request #797
Opened 2022-09-07 14:06 UTC by guruevi

##### SUMMARY
Creating a new host with an IPv6 address returns an error on Zabbix (invalid IP). Limiting the output to the first IPv4 address.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
community.zabbix.zabbix_agent

##### ADDITIONAL INFORMATION
Order of IP addresses is not guaranteed on Windows:
```
    "hostvars[inventory_hostname]['ansible_ip_addresses']": [
        "fe80::xxxx:xxxx:xxxx:xxxx%x",
        "10.0.0.1"
    ]
```
Resulting in
`"msg": "Failed to create host myhost: ('Error -32602: Invalid params., Invalid IP address \"fe80::xxxx:xxxx:xxxx:xxxx%x\"`

2022-09-09 20:27 UTC, mu1f407 approved these changes
Thanks @guruevi!

2022-09-09 21:55 UTC, pyrodie18 approved these changes

2022-09-09 21:57 UTC, pyrodie18 requested changes
Please include a changelog fragment.  I expect this would be a `bugfixes`

2022-09-09 22:09 UTC, guruevi commented
Added item in Changelog.

2022-09-10 00:45 UTC, pyrodie18 commented
> 

Sorry, I should have posted this link (https://docs.ansible.com/ansible/latest/community/development_process.html#creating-changelog-fragments).  Please revert the change to CHANGELOG.rst (it'll get overwritten next time we run the changelog).  You'll need to create a yml file in changelogs/fragments/.  You can find an example at https://github.com/ansible-collections/community.zabbix/blob/main/changelogs/fragments/786-web-add-ubuntu-22-04-support.yml.  Rather than `minor_change`, you'll be doing `bugfixes` for the category.  After that, we should be good.  Sorry for the confusion and we appreciate your time.

2022-09-10 07:59 UTC, D3DeFi approved these changes
Looks good now, thanks!

2022-09-10 07:59 UTC, merged