Add missing variants for SNMPv3 authprotocol and privprotocol.
ansible-collections/community.zabbix pull request #880
Opened 2023-01-18 11:34 UTC by KarlikB

##### SUMMARY
Current zabbix_host module allows to set SNMPv3 authprotocol and privprotocol only to values 0,1,2 as it was possible in Zabbix 5.0. Zabbix 6.0 allow to set 6 variants as described on page https://www.zabbix.com/documentation/6.0/en/manual/api/reference/hostinterface/object
This pull request adds missing variants

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
module zabbix_host

##### ADDITIONAL INFORMATION
I have modified only zabbix_host.py file, please check if this change needs to be done also in other places (documentation?)

2023-01-18 12:46 UTC, BGmot commented
Thank you for the PR! We have to support Zabbix 4.0 and 5.0, please make a note that not all added protocols supported in these versions. Also would be nice to have at least one test added for one of protocols you added.
And please add a CHANGELOG fragment.

2023-01-18 13:19 UTC, BGmot commented
Thanks for your new commits. And a test please somewhere after this one https://github.com/ansible-collections/community.zabbix/blob/main/tests/integration/targets/test_zabbix_host/tasks/zabbix_host_tests.yml#L880

2023-01-18 13:29 UTC, KarlikB commented
> Thanks for your new commits. And a test please somewhere after this one https://github.com/ansible-collections/community.zabbix/blob/main/tests/integration/targets/test_zabbix_host/tasks/zabbix_host_tests.yml#L880

I modified existing test you mentioned to use new variant in case Zabbix version >= 5.4
Is it acceptable this way?
```- name: "test: update details for SNMPv3 interface"
      zabbix_host:
        host_name: ExampleHost
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: 10.1.1.1
            port: "10050"
          - type: 2
            main: 1
            useip: 1
            ip: 10.1.1.1
            port: "161"
            details:
              version: 3
              contextname: snmp_context
              securityname: SNMP3 sec name
              securitylevel: 2
              authprotocol: {{ 2 if zabbix_version | float >= 5.4 else 0 }}
              authpassphrase: secret_auth_passphrase
              privprotocol: {{ 2 if zabbix_version | float >= 5.4 else 0 }}
              privpassphrase: secret_priv_passphrase
      register: zabbix_host1```

2023-01-18 17:47 UTC, KarlikB commented
@BGmot Hi, my latest changes finally goes through all checks

2023-01-18 17:58 UTC, BGmot requested changes

2023-01-18 17:58 UTC, BGmot commented on changelogs/fragments/880.yml
> +  - lineinfile - Added missing variants for SNMPv3 authprotocol and privprotocol introduced by Zabbix 6
Please let's follow https://docs.ansible.com/ansible/latest/community/development_process.html#changelog-fragment-entry-format and change "scope":
```suggestion
  - zabbix_host - add missing variants for SNMPv3 authprotocol and privprotocol introduced by Zabbix 6
```

2023-01-18 19:17 UTC, BGmot approved these changes
Looks good to me. Thanks!

2023-01-19 08:53 UTC, D3DeFi approved these changes
Good patch, thank you!

2023-01-19 08:53 UTC, merged